apiVersion: apps/v1
kind: Deployment
metadata:
  name: boilerplate
spec:
  selector:
    matchLabels:
      app: boilerplate
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: boilerplate
    spec:
      containers:
      - name: boilerplate #dockertestapp
        image: rupaknepal/spring-boot-boilerplate:latest #rupaknepal/dockertestapp:jboss-wildfly
        ports:
        - containerPort: 8080


