apiVersion: v1
kind: Service
metadata:
  name: boilerplate
  annotations:
    isDiscoverable: "true"
spec:
  type: NodePort
  selector:
    app: boilerplate
  ports:
    - name: client
      protocol: TCP
      port: 8080
      targetPort: 8080
